### ISSUE TITLE
PDF output has wrong font

### ISSUE THREAD

**Issue by blairjanis** [williamkapke/ipp#76]
I'm printing a PDF that on some pages uses Times New Roman.  Using IPP, on one of the printers the font is converted to Courier New (or something like that) and on another it is converted to some Sans Serif font (maybe Arial).  Printing from Acrobat gives me the correct result.  Printing through IPP does not.  I've tried on linux and mac os.  Same result.

**Comment by michaelrsweet** [comment]
@blairjanis Can you attach a sample PDF that isn't printing correctly?

FWIW, this isn't an issue with IPP but an issue with either the PDF or the printers you are using. My guess is that the fonts are not embedded in the PDF leading to these issues...

**Comment by blairjanis** [comment]
Sure.  There is some confidential personal information on the pdf so I’ll
need to redact that.  And hopefully not “fix” the problem by doing so.  I’m
just getting back to the office and will get to it.

**Comment by blairjanis** [comment]
The pdf has some confidential information in it so I can't post it here.  I'm exploring the embedding issue but that doesn't seem to be getting me anywhere.

**Comment by michaelrsweet** [comment]
FWIW, the PDF spec only requires printers to have the core PostScript fonts, which means Times Roman (not Times New Roman), which is why I suspect a font embedding issue... Not sure if there is a way for you to install fonts through the printer's web interface, but that might also resolve things for you...

**Comment by wifiprintguy** [comment]
I agree with @michaelrsweet - since "printing from Acrobat" works, likely what is happening is that opening the PDF in Acrobat causes Acrobat to generate an altered / augmented PDF stream that includes the needed font glyphs / definitions, and that is why it gets renders properly on the printer. To confirm, open in Acrobat, and export to a new PDF, and if that is sent via IPP and prints properly, then that is likely the explanation.

**Comment by blairjanis** [comment]
Thanks for all the suggestions.  This is indeed an issue between the PDF and the printer.  I was able to resolve it through font embedding at the source.  Thanks for the help.
